### ISSUE TITLE
demos/bubblewrap-shell does not work

### ISSUE THREAD

**Issue by leeming** [projectatomic/bubblewrap#100]
Running demos/bubblewrap-shell on bubblewrap 0.1.2 gets the following error

```
$ ./bubblewrap-shell.sh 
execvp /bin/sh: No such file or directory
```

Not running a Fedora distro, in case that is an issue?

```
Distributor ID: Debian
Description:    Debian GNU/Linux 8.4 (jessie)
Release:    8.4
Codename:   jessie
```

I have been getting loads of related errors to the above while using bweap, but thought I would make sure some of the demos worked first

**Comment by leeming** [comment]
as pointed out on IRC, the issue here is likely due to debian file system organisation. I will investigate/correct paths and report back

**Comment by leeming** [comment]
Playing with the paths and adding in /lib mounts fixed this issue


```
set -uo pipefail
(exec bwrap --ro-bind /usr /usr \
      --ro-bind /lib /lib \
      --ro-bind /lib64 /lib64 \
      --ro-bind /bin /bin \
      --dir /tmp \
      --proc /proc \
      --dev /dev \
      --ro-bind /etc/resolv.conf /etc/resolv.conf \
      --chdir / \
      --unshare-pid \
      --dir /run/user/$(id -u) \
      --setenv XDG_RUNTIME_DIR "/run/user/`id -u`" \
      --file 11 /etc/passwd \
      --file 12 /etc/group \
      /bin/sh) \
    11< <(getent passwd $UID 65534) \
    12< <(getent group $(id -g) 65534)
```

I would submit extra demo as a PR, but there is still a minor issue that I am unsure of. When exiting the sandbox, I get the following error

> /bin/sh: 0: Cannot set tty process group (No such process)

**Comment by cgwalters** [comment]
Marking this one as closed per last comment.
