### ISSUE TITLE
bash: /dev/null: Permission denied

### ISSUE THREAD

**Issue by miabbott** [projectatomic/bubblewrap#125]
While testing https://bodhi.fedoraproject.org/updates/bubblewrap-0.1.4-5.fc25 on a F25 Vagrant box, I observed the following:

```
$ rpm -q bubblewrap
bubblewrap-0.1.4-5.fc25.x86_64
$ whoami
vagrant
$ bwrap --ro-bind / / bash
bash: /dev/null: Permission denied
bash: /dev/null: Permission denied
bash: /dev/null: Permission denied
bash: /dev/null: Permission denied
bash: /dev/null: Permission denied
bash: /dev/null: Permission denied
bash: /dev/null: Permission denied
bash: /dev/null: Permission denied
bash: /dev/null: Permission denied
bash: /dev/null: Permission denied
bash: /dev/null: Permission denied
bash: /dev/null: Permission denied
bash: /dev/null: Permission denied
bash: /dev/null: Permission denied
bash: /dev/null: Permission denied
bash: /dev/null: Permission denied
bash: /dev/null: Permission denied
```

Despite the errors, the operation appeared successful.

**Comment by cgwalters** [comment]
Yeah, we basically can't sanely support binding the full host `/` in.  I'm tempted to make it a fatal error.  Try [the demo script](https://github.com/projectatomic/bubblewrap/blob/master/demos/bubblewrap-shell.sh).

**Comment by cgwalters** [comment]
Oh, this is in the README.  Will fix.

**Comment by miabbott** [comment]
> Oh, this is in the README. Will fix.

Yeah, that was what I was following.  Thanks for updating.
