### ISSUE TITLE
README: citation needed

### ISSUE THREAD

**Issue by hasufell** [projectatomic/bubblewrap#130]
> These tools are not suitable to give to unprivileged users, because it is trivial to turn such access into to a fully privileged root shell on the host.

Broad claim. I don't see any evidence here.

**Comment by alexlarsson** [comment]
These are not contended statements, ask any docker developer (me for instance), or look in the docker for instance. For instance, the docker run with --privileged and -v /:/host_root will give you full privileges and access to the full host filesystem. systemd-nspawn similarly lets you set up minimally contained container (of course, systemd-nspawn requires you to be root to run it, so its not technically a privilege escalation).

**Comment by hasufell** [comment]
> For instance, the docker run with --privileged and -v /:/host_root will give you full privileges and access to the full host filesystem

Running everything with `--privileged` is simply misconfiguration, not an architectural problem, even less a vulnerability.

**Comment by alexlarsson** [comment]
I don't understand what you mean by that. If you give your user access to the docker socket he can use --privileged to get access, there is nothing unexpected or "vulnerability" in this. It is just something implied by having docker access. But, that also means you can't generally give out docker access to users you don't trust with root.
