### ISSUE TITLE
Allow dropping all capabilities inside the jail

### ISSUE THREAD

**Issue by sonicou** [projectatomic/bubblewrap#136]
When using user namespaces to create a jail, I still have access to capabilities like CAP_SYS_ADMIN

I would like to be able to tell the wrapper to drop all capabilities without exceptions when run as a normal user. 

Please note that user namespaces reset capabilities. Inside a user namespace all capabilities are available to the user by default

**Comment by alexlarsson** [comment]
bubblewrap never leaves you with any capabilities in the sandbox, user namespaces or not. We do have a PR (https://github.com/projectatomic/bubblewrap/pull/101) which adds this feature, but its under discussion.

Did you see this happening? If so, that would be a bug.

**Comment by sonicou** [comment]
When testing available capabilities inside bubblewrap, using faudit from firejail, there seem to be all capabilities available:

```
BAD: the capability map is 3fffffffff, it should be all zero. Use "firejail --caps.drop=all" to fix it.
UGLY: CAP_SYS_ADMIN is enabled.
UGLY: CAP_SYS_BOOT is enabled.
```

Here is the testcode: 
https://github.com/netblue30/firejail/blob/master/src/faudit/caps.c


Firejail drops caps alike this:

```
    unsigned long cap;
    for (cap=0; cap <= 63; cap++) {
		int code = prctl(PR_CAPBSET_DROP, cap, 0, 0, 0);
		if (code == -1 && errno != EINVAL){
			printf("ERROR PR_CAPBSET_DROP\n");
			return;
		}
    }
```

Seems there is something broken in bubblewrap in that regard

**Comment by alexlarsson** [comment]
That just checks the bounding set, a bubblewrap process looks like this in /proc/pid/status:

```
CapInh:	0000000000000000
CapPrm:	0000000000000000
CapEff:	0000000000000000
CapBnd:	0000003fffffffff
CapAmb:	0000000000000000
```
True, the bounding set is all set, but the effective set is 0, and this can only be increased by setuid operations, which are neutered by PR_NO_NEW_PRIVS.

Still, i wouldn't hurt to drop the bounding set too.

**Comment by cgwalters** [comment]
Yeah, `PR_NO_NEW_PRIVS` is stronger because it also ensures the process doesn't gain "uid 0 but no capabilities", which could be used to attack the host system if anything is mounted read-write from it.

**Comment by cgwalters** [comment]
This was done in https://github.com/projectatomic/bubblewrap/commit/b35f84a33199ab09ff916f90df131ee91dc0ff68

**Comment by mariospr** [comment]
This broke flatpak on our ARM product because, apparently, the calling thread doesn't have the CAP_SETPCAP capability. So, while I try to find out why that's the case for our ARM kernel only (it works fine on amd64), I was wondering if bubblewrap should check whether that's the case before calling `prctl()`? 

More details in As mentioned in https://github.com/projectatomic/bubblewrap/pull/149#issuecomment-277667073,
