### ISSUE TITLE
mount flags

### ISSUE THREAD

**Issue by valoq** [projectatomic/bubblewrap#138]
When using mount() inside of bubblewrap, there is always the MS_MGC_VAL flag.

However:
> Specifying MS_MGC_VAL was required in kernel versions prior to 2.4, but since Linux 2.4 is no longer required and is ignored if specified.

http://man7.org/linux/man-pages/man2/mount.2.html

Is there still a reason it is used?

**Comment by alexlarsson** [comment]
No real reason, but on the other hand it doesn't hurt. (Not that bwrap would run on pre-2.4 kernels though.)

**Comment by valoq** [comment]
Thanks
