### ISSUE TITLE
setsid() workaround in 0.1.6 breaks interactive terminals

### ISSUE THREAD

**Issue by alexlarsson** [projectatomic/bubblewrap#147]
The change in https://github.com/projectatomic/bubblewrap/pull/143 breaks the use of bwrap for interactive sessions. For instance, if you run `bwrap --bind / / sh`, and then press `ctrl-Z`the "outer" shell gets unfrozen, but the "inner" shell doesn't get frozen, and both try to read terminal input at the same time.

**Comment by alexlarsson** [comment]
Another problem is that if you do  `bwrap  --bind / / sleep 1000` and then `ctrl-C`, then the sleep process keeps running.

**Comment by alexlarsson** [comment]
I've looked into this for various other ways to work around this, but I think the seccomp way is the only realistic one, so i started looking at that.

**Comment by cgwalters** [comment]
Fixed by https://github.com/projectatomic/bubblewrap/pull/154
