### ISSUE TITLE
Inappropriate ioctl for device

### ISSUE THREAD

**Issue by valoq** [projectatomic/bubblewrap#148]
version 0.1.6 produces the following error message:

`./bwrap --bind / / --proc /proc --dev /dev bash`

bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell

Everything still appears to work.

Tested on debian (nosuid) and arch (with and without suid)

**Comment by alexlarsson** [comment]
Yeah, this is part of a regression:
https://github.com/projectatomic/bubblewrap/issues/147
