### ISSUE TITLE
Nested bubblewrap

### ISSUE THREAD

**Issue by robsmith11** [projectatomic/bubblewrap#164]
Is there any reason bwrap can't be run inside another bwrap with a kernel that supports user namespaces?

It would nice to have the ability just like chroot can run inside another chroot.
My use case is compiling software in an isolated environment in a dev environment that is itself running in bwrap.

**Comment by alexlarsson** [comment]
I believe this is possible, but only if your kernel supports unprivileged user namespaces, because any form of setuid is prohibited in the sandbox.

**Comment by robsmith11** [comment]
That was my expectation, but I'm getting an "operation not permitted" error when I try it.  My bwrap does not have setuid and works fine as an unprivileged user when not nested.

**Comment by valoq** [comment]
This won't work because capabilities are dropped, which is a good thing.
Even if it were possible with the current setup, I am not sure it would be wise to allow sandboxed processes to create new namespaces.

**Comment by alexlarsson** [comment]
You should not need capabilties in the outer (middle) namespace to be able to use unprivileged user namespaces. Not sure why this is not working.

**Comment by robsmith11** [comment]
#256 has made this work! :)
