### ISSUE TITLE
bwrap --version fails in LXC

### ISSUE THREAD

**Issue by ncopa** [projectatomic/bubblewrap#185]
The flatpak configure script will run a test `bwrap --version` to verify that the versino is new enough. However, when building flatpack in lxc with some capabilities dropped the following error happens:

````
checking pkg-config is at least version 0.24... yes
capset failed: Operation not permitted
configure: error: You need at least version 0.1.5 of bubblewrap to use the system installed version
````

I could give more capabilities to the container but I think there should be no real reason to require that just to print the version.

**Comment by cgwalters** [comment]
PR in https://github.com/projectatomic/bubblewrap/pull/187
