### ISSUE TITLE
/dev/fd symlink should be created when using --dev

### ISSUE THREAD

**Issue by robsmith11** [projectatomic/bubblewrap#191]
When I was running some install scripts inside bwrap, I ran into a problem because I was missing the /dev/fd symlink.  It's easily fixed with `ln -s /proc/self/fd /dev/fd`, but it seems like it should be automatically created when bwrap is called with --dev.

**Comment by cgwalters** [comment]
PR in https://github.com/projectatomic/bubblewrap/pull/207
