### ISSUE TITLE
Feline mascot is non-free

### ISSUE THREAD

**Issue by smcv** [projectatomic/bubblewrap#204]
While looking for vaguely relevant images to illustrate a talk on Flatpak, I discovered that the bubblewrapped cat in bubblewrap.jpg is licensed with no derivatives allowed. Sadly this is not a Free license.

I propose replacing it with one of these well-protected felines: https://www.flickr.com/photos/donabelandewen/4106414108/ https://www.flickr.com/photos/quinnanya/128222244/ https://www.flickr.com/photos/chatblanc1/5069751223/

or this extremely safe dog: https://www.flickr.com/photos/28879143@N05/2700798155/in/photolist-5HL9TQ-8qdny-8qdnz-57Eicr-6dCF8

(sadly I was unable to find a bubblewrapped ferret, perhaps because they never stay still for long enough)

**Comment by cgwalters** [comment]
None of those are under a CC license that's listed as compatible in <https://wiki.debian.org/DFSGLicenses> as far as I can see.

Dunno.  We could just remove it?  I'd be a little sad but OTOH it's really not worth fighting for.

**Comment by smcv** [comment]
Ugh, yes, I was misremembering: I thought CC-BY(-SA) >= 2 was OK but actually it's only >= 3 that Debian accepts.

**Comment by cgwalters** [comment]
PR in https://github.com/projectatomic/bubblewrap/pull/206
