### ISSUE TITLE
bwrap fails to create user namespace with kernel-3.10.0-693.2.2.el7.x86_64

### ISSUE THREAD

**Issue by TristanCacqueray** [projectatomic/bubblewrap#216]
Hi,

With kernel-3.10.0-514.26.1.el7.x86_64 (CentOS-7.3), this command works:
```
$ bwrap --unshare-all --ro-bind / / /bin/id
uid=1000(centos) ...
```

With kernel-3.10.0-693.2.2.el7.x86_64 (CentOS-7.4), this command fails:
```
$ bwrap --unshare-all --ro-bind / / /bin/id
Creating new namespace failed, likely because the kernel does not support user namespaces.  bwrap must be installed setuid on such systems.
```

It seems like previously, the file _/sys/module/user_namespace/parameters/enable_ was set to 'N' by default,
and it doesn't exist anymore.

**Comment by simonmysun** [comment]
Hi, I'm experiencing a same issue in 3.10.0-1062.18.1.el7.x86_64, Does ec5093d also work for this kernel?
