### ISSUE TITLE
Need a way to report errors of bubblewrap separately

### ISSUE THREAD

**Issue by gtristan** [projectatomic/bubblewrap#257]
Currently when launching bubblewrap to execute a command; there is no way to distinguish between errors encountered by the child process and errors bubblewrap encountered while setting up the sandbox.

It would be nice to be able to collect these errors separately.

**Comment by rhatdan** [comment]
podman and docker follow the standard set by chroot
```
info chroot
...
   ‘chroot’ is installed only on systems that have the ‘chroot’
function, so portable scripts should not rely on its existence.

   Exit status:

     125 if ‘chroot’ itself fails
     126 if COMMAND is found but cannot be invoked
     127 if COMMAND cannot be found
     the exit status of COMMAND otherwise
```

**Comment by gtristan** [comment]
@rhatdan Indeed something similar would be good.

From the perspective of BuildStream, where we use `bwrap` for build sandbox containerization and also for running commands on behalf of the user in a shell environment we construct; this is not ideal in the most pragmatic sense.

I.e. we cannot be in control of what the user invokes, or what software is in the user's sandbox, so if the user decides to call something which legitimately returns `125`, `126` or `127`; then there is no way for us to inform the user that the program they invoked failed, instead we would assume it was a `bwrap` failure (and indeed, it could very well be that the user makes a naive attempt to call `chroot` inside the `bwrap` sandbox, in which case it will almost certainly report `125`).

That said, I feel this is corner case enough that it doesnt matter all that much.

**Comment by rhatdan** [comment]
Yup every package has the same issue including chroot calling chroot :^)  But I agree this is a corner case which the user would be forced to figure out, and  a hell of a lot better then what you have now.

**Comment by cgwalters** [comment]
Emulating the `chroot` standard seems like a good idea to me, that said today we have `--info-fd` which seems under-documented; right now it just has the child PID, but we could easily extend it to include precise details like this.

**Comment by domabrown** [comment]
I'm working on a patch for this atm, would it be OK for us to reuse the info-fd to print out a JSON block with the child exit code prior to the parent exiting?
