### ISSUE TITLE
Can't see any installation guide, am I miss something

### ISSUE THREAD

**Issue by duxinxiao** [projectatomic/bubblewrap#274]
I cant install it from apt-get, Is there any easy way?

**Comment by cgwalters** [comment]
Looks like there's a [Debian testing package](https://packages.debian.org/buster/bubblewrap).  In general we're not going to provide pre-built binaries here; please talk to your distribution about packages.  If you're on Debian/Ubuntu it seems likely you can install from that package.  I hope that helps!

**Comment by smcv** [comment]
In general, please obtain packages of OS-level components like bubblewrap for a particular distribution from that distribution. If your distribution doesn't have bubblewrap packaged, that's a feature request to be sent to that distribution.

> Looks like there's a [Debian testing package](https://packages.debian.org/buster/bubblewrap)

That page also has links to bubblewrap packages for bubblewrap on Debian 8 'jessie' (as a backport from Debian 9 'stretch'), Debian 9 'stretch' (and an updated version available as a backport), and newer branches. bubblewrap is also available in the `universe` package repositories for Ubuntu 17.10 'artful' or later, including Ubuntu 18.04 LTS 'bionic'.

**Comment by duxinxiao** [comment]
Thanks for help, I think I know what I should do
