### ISSUE TITLE
Issue in bubblewrap-0.2.0

### ISSUE THREAD

**Issue by Abinayasandhiya** [projectatomic/bubblewrap#276]
Hi,

We are trying to build bubblewrap-0.2.0 on RedHat 6 machine.
Please find below server details.
***********************************************************************************************************
[root@abinaya-r6 ~]$ cat /etc/redhat-release
Red Hat Enterprise Linux Server release 6.8 (Santiago)

[root@abinaya-r6 ~]$ gcc --version
gcc (GCC) 7.2.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
**********************************************************************************************************

The steps which is we tried to build bubblewrap is below:

**********************************************************************************************************
Step 1: We downloaded the tar file of bubblewrap.
Step 2: Installed all the required below dependencies:
          yum install git autoconf automake libtool libcap-devel libxslt docbook-style-xsl

Step 3: Done below build step without any issue.
          ./configure

Step 4: when we run "make" facing below issue:

`[root@abinaya-nsn-r6 bubblewrap-0.2.0]$ make
make  all-am
make[1]: Entering directory `/root/bubblewrap-0.2.0'
  CC       bwrap-bubblewrap.o
In file included from /usr/include/sys/prctl.h:23:0,
                 from ./bubblewrap.c:32:
/usr/include/linux/prctl.h:134:2: error: unknown type name ‘__u64’
  __u64 start_code;  /* code section bounds */
  ^~~~~
/usr/include/linux/prctl.h:135:2: error: unknown type name ‘__u64’
  __u64 end_code;
  ^~~~~
/usr/include/linux/prctl.h:136:2: error: unknown type name ‘__u64’
  __u64 start_data;  /* data section bounds */
  ^~~~~
/usr/include/linux/prctl.h:137:2: error: unknown type name ‘__u64’
  __u64 end_data;
  ^~~~~
/usr/include/linux/prctl.h:138:2: error: unknown type name ‘__u64’
  __u64 start_brk;  /* heap for brk() syscall */
  ^~~~~
/usr/include/linux/prctl.h:139:2: error: unknown type name ‘__u64’
  __u64 brk;
  ^~~~~
/usr/include/linux/prctl.h:140:2: error: unknown type name ‘__u64’
  __u64 start_stack;  /* stack starts at */
  ^~~~~
/usr/include/linux/prctl.h:141:2: error: unknown type name ‘__u64’
  __u64 arg_start;  /* command line arguments bounds */
  ^~~~~
/usr/include/linux/prctl.h:142:2: error: unknown type name ‘__u64’
  __u64 arg_end;
  ^~~~~
/usr/include/linux/prctl.h:143:2: error: unknown type name ‘__u64’
  __u64 env_start;  /* environment variables bounds */
  ^~~~~
/usr/include/linux/prctl.h:144:2: error: unknown type name ‘__u64’
  __u64 env_end;
  ^~~~~
/usr/include/linux/prctl.h:145:2: error: unknown type name ‘__u64’
  __u64 *auxv;   /* auxiliary vector */
  ^~~~~
In file included from ./bubblewrap.c:34:0:
/usr/include/linux/seccomp.h:50:2: error: unknown type name ‘__u64’
  __u64 instruction_pointer;
  ^~~~~
/usr/include/linux/seccomp.h:51:2: error: unknown type name ‘__u64’
  __u64 args[6];
  ^~~~~
In file included from ./bubblewrap.c:35:0:
/usr/include/linux/filter.h:24:2: error: unknown type name ‘__u16’
  __u16 code;   /* Actual filter code */
  ^~~~~
/usr/include/linux/filter.h:25:2: error: unknown type name ‘__u8’
  __u8 jt; /* Jump true */
  ^~~~
/usr/include/linux/filter.h:26:2: error: unknown type name ‘__u8’
  __u8 jf; /* Jump false */
  ^~~~
./bubblewrap.c: In function ‘write_uid_gid_map’:
./bubblewrap.c:769:45: error: ‘O_PATH’ undeclared (first use in this function); did you mean ‘_CS_PATH’?
   dir_fd = openat (proc_fd, dir, O_RDONLY | O_PATH);
                                             ^~~~~~
                                             _CS_PATH
./bubblewrap.c:769:45: note: each undeclared identifier is reported only once for each function it appears in
./bubblewrap.c: In function ‘main’:
./bubblewrap.c:2045:39: error: ‘O_PATH’ undeclared (first use in this function); did you mean ‘_CS_PATH’?
   proc_fd = open ("/proc", O_RDONLY | O_PATH);
                                       ^~~~~~
                                       _CS_PATH
make[1]: *** [bwrap-bubblewrap.o] Error 1
make[1]: Leaving directory `/root/bubblewrap-0.2.0'
make: *** [all] Error 2
`

***********************************************************************************************************

Can anyone let me know is there anything i missed to install / is this bubblewrap cannot work on RHEL6.
Because the same version of bubblewrap is working on RedHat 7 machine.

Issue is only on RedHat 6 and tried lot to fix but no luck.

Help me on this.

Regards,
Abinaya

**Comment by cgwalters** [comment]
Sorry, we are never going to support using bwrap on RHEL6.  It simply doesn't have the requisite container features.

I'd recommend moving your RHEL6 workload into a container and running it on a RHEL7 kernel.  That's fully supported by Red Hat; there's a `registry.access.redhat.com/rhel6` container image available.

**Comment by cgwalters** [comment]
If you still want bwrap in RHEL6 *userspace* (e.g. that container image above)  on a newer kernel...that's perhaps possible but I doubt anyone contributing to bwrap today is going to leap to working on it, but if someone provided patches they'd be considered.
