### ISSUE TITLE
--cwd is mentioned in man page, but not supported

### ISSUE THREAD

**Issue by kparal** [projectatomic/bubblewrap#291]
The man page says:

> ENVIRONMENT
>        HOME
>            Used as the cwd in the sandbox if **--cwd** has not been explicitly specified and the current
>            cwd is not present inside the sandbox. The --setenv option can be used to override the
>            value that is used here.
> 

However:
```
$ bwrap --cwd test test
bwrap: Unknown option --cwd
```

I can't figure out how to set cwd without overriding `$HOME`. `--cwd` is not supported and `--setenv PWD dir` doesn't seem to have any effect. `--setenv HOME dir` works, but it has annoying consequences, like mixing your home directory files with the program directory files. If you intend to keep a persistent directory for the sandboxed program, this basically forces you to have its files exploded directly in the home dir.

Can you please either implement `--cwd` as indicated, or perhaps follow `$PWD` value?

bubblewrap-0.3.0-2.fc28.x86_64

**Comment by smcv** [comment]
The man page is wrong, the real option is `--chdir` (as per `bwrap --help`).

**Comment by smcv** [comment]
In fact `--chdir` is already documented elsewhere in the man page, just not in the sentence you were looking at.

**Comment by kparal** [comment]
> In fact `--chdir` is already documented elsewhere in the man page, just not in the sentence you were looking at.

I completely missed that. Thanks for the documentation fix.
