### ISSUE TITLE
OpenGL does not work in the most permissive settings. 

### ISSUE THREAD

**Issue by Barafu** [projectatomic/bubblewrap#297]
If I run `mpv` on my system, it uses opengl output and I get this:
```
mpv video/Benny\ Hill\ Theme\ -\ Microwave\ Guitar\ Cover-OyuIgh_Ip74.webm 
Playing: video/Benny Hill Theme - Microwave Guitar Cover-OyuIgh_Ip74.webm
 (+) Video --vid=1 (*) (vp9 1920x1080 25.000fps)
 (+) Audio --aid=1 --alang=eng (*) (opus 2ch 48000Hz)
AO: [jack] 48000Hz stereo 2ch floatp
VO: [gpu] 1920x1080 yuv420p
AV: 00:00:01 / 00:00:33 (4%) A-V: -0.011 DS: 2.487/0
```
 but if I run it as:
```
bwrap --bind / / /bin/bash
mpv video/Benny\ Hill\ Theme\ -\ Microwave\ Guitar\ Cover-OyuIgh_Ip74.webm 
```
then mpv can not initialise video card and I get this:
```
mpv video/Benny\ Hill\ Theme\ -\ Microwave\ Guitar\ Cover-OyuIgh_Ip74.webm 
Playing: video/Benny Hill Theme - Microwave Guitar Cover-OyuIgh_Ip74.webm
 (+) Video --vid=1 (*) (vp9 1920x1080 25.000fps)
 (+) Audio --aid=1 --alang=eng (*) (opus 2ch 48000Hz)
[vo/gpu/x11] X11 error: BadValue (integer parameter out of range for operation)
[vo/gpu/x11] Type: 0, display: 0x7fd7a8225100, resourceid: 0, serial: 6c                                                                                                  
[vo/gpu/x11] Error code: 2, request code: 97, minor code: 3                                                                                                               
[vo/gpu] Could not create GLX context!
libEGL warning: DRI2: failed to authenticate
[vo/gpu/opengl] Suspected software renderer or indirect context.
[vo/gpu/x11] X11 error: BadValue (integer parameter out of range for operation)
[vo/gpu/x11] Type: 0, display: 0x7fd7a8318df0, resourceid: 0, serial: 6c
[vo/gpu/x11] Error code: 2, request code: 97, minor code: 3
[vo/gpu] Could not create GLX context!
[vo/gpu/vulkan] vkEnumeratePhysicalDevices(vk->inst, &num, NULL): VK_ERROR_INITIALIZATION_FAILED
[vo/vdpau] Error when calling vdp_device_create_x11: 1
[vo/xv] Warning: this legacy VO has bad quality and performance, and will in particular result in blurry OSD and subtitles. You should fix your graphics drivers, or not force the xv VO.
AO: [jack] 48000Hz stereo 2ch floatp
VO: [xv] 1920x1080 yuv420p
AV: 00:00:00 / 00:00:33 (0%) A-V: -0.039 DS: 2.500/0
[vo/xv] X11 can't keep up! Waiting for XShm completion events...
AV: 00:00:08 / 00:00:33 (24%) A-V: -0.256 DS: 14.770/323
```
I thought bwrap in this mode should not interfere with anything. Can I do something to make it work? I was going to use bwrap to run some Wine applications that use Unity for interface, but without full video acceleration it would not work.

**Comment by smcv** [comment]
What you quoted is not the most permissive setting. The most permissive setting would be `--dev-bind / /`, which does not mount it `nodev`.

Using `--bind / / --dev-bind /dev /dev` is slightly more restrictive but also a lot more reasonable.

**Comment by smcv** [comment]
A simpler example, using `/dev/urandom` and `xxd` rather than OpenGL devices and `mpv`:

```
% bwrap --bind / / -- sh -c 'head -c1 /dev/urandom | xxd' 
head: cannot open '/dev/urandom' for reading: Permission denied
% bwrap --dev-bind / / -- sh -c 'head -c1 /dev/urandom | xxd'
00000000: 53                                       S
```

**Comment by tarkov2213** [comment]
I cannot figure out what is preventing opengl from working.

When you use --bind / / --dev-bind /dev /dev
then opengl is working 
it even works with --ro-bind / / --dev /dev --dev-bind /dev/dri /dev/dri

but when being more selective with ro-binds  it stops working

does opengl need access to some additional sockets somewhere? if so, they where?

with glxgears the errors are:

libGL error: MESA-LOADER: failed to retrieve device information
libGL error: Version 4 or later of flush extension not found
libGL error: failed to load driver: i915


with mpv: 

libEGL warning: MESA-LOADER: failed to retrieve device information

[vo/gpu/opengl] Suspected software renderer or indirect context.

**Comment by charmander** [comment]
@tarkov2213 Can you give examples of “more selective with ro-binds”?

**Comment by tarkov2213** [comment]
@charmander

  --unshare-all
  --cap-drop ALL
  --new-session
  --die-with-parent
  --hostname bwrap
  --dev /dev
  --dev-bind /dev/dri /dev/dri
  --dev-bind /dev/snd /dev/snd
  --proc /proc
  --tmpfs /tmp
  --ro-bind /usr/lib /usr/lib
  --ro-bind /usr/lib64 /usr/lib64
  --ro-bind /usr/share /usr/share
  --ro-bind /lib /lib
  --ro-bind /lib64 /lib64
  --ro-bind /usr/bin/mpv /usr/bin/mpv
  --ro-bind /etc /etc
  --ro-bind /tmp/.X11-unix/X0 /tmp/.X11-unix/X0

**Comment by tarkov2213** [comment]
For anyone who stumbled onto this problem, the solution is:

```
  --ro-bind /sys/dev/char /sys/dev/char
  --ro-bind /sys/devices/pci0000:00 /sys/devices/pci0000:00
```

need both
