### ISSUE TITLE
Install bubblewrap on Debian 8/Jessie from sources

### ISSUE THREAD

**Issue by RogerTarani** [projectatomic/bubblewrap#301]
How to install bubblewrap from sources on Linux (Debian 8/Jessie)?
bubblewrap is not available from Debian 8/Jessie package manager.
It is available for Debian 9/Stretch [https://packages.debian.org/stretch/bubblewrap](https://packages.debian.org/stretch/bubblewrap)
And I don't succeed in installing bubblewrap from sources with the usual`$ ./configure && make && make install`.

What am I missing?
Thanks

EDIT
Adding `deb http://ftp.debian.org/debian jessie-backports main` to `/etc/apt/sources.list` solved the problem:
$ sudo apt-get -t jessie-backports install bubblewrap

However I would like to know how to install bubblewrap from sources.

**Comment by TingPing** [comment]
> And I don't succeed in installing bubblewrap from sources with the usual$ ./configure && make && make install.

Well what error you do get...

**Comment by RogerTarani** [comment]
1/ I can't find a configure file in all the three archives  

2/ When cloning the source an executing ./autogen.sh it gives me the following: [bubblewrap_autogen.txt](https://github.com/projectatomic/bubblewrap/files/2706104/bubblewrap_autogen.txt)

**Comment by TingPing** [comment]
> 1/ I can't find a configure file in all the three archives

Well its there, I don't know what more to say.

> 2/ When cloning the source and executing ./autogen.sh it gives me the following: bubblewrap_autogen.txt

That looks like a partial log; Post the full log and `config.log`.

**Comment by TingPing** [comment]
> checking for sys/capability.h... no
configure: error: *** POSIX caps headers not found

Find the package providing the `sys/capability.h` file and install it. You will likely hit further failures. `apt-get build-dep bubblewrap` or such will probably be a big help.

**Comment by TingPing** [comment]
> Is it normal that there is no file configure in bubblewrap-0.3.1.zip and v0.3.1.tar.gz projectatomic/bubblewrap/releases ?

Yes those are generated by github from sources only and can't be disabled. The tar.xz is the one made by the maintainer with the correct contents.

**Comment by clarus** [comment]
> Yes those are generated by github from sources only and can't be disabled. The tar.xz is the one made by the maintainer with the correct contents.

I would add a `-full` to explicit that this archive contains more than the sources from Git. For example: `bubblewrap-full-0.3.1.tar.xz`. I have seen this convention used in [OPAM](https://github.com/ocaml/opam/releases):

![image](https://user-images.githubusercontent.com/316665/56906241-1caf2f80-6aa2-11e9-86d5-85191ff20329.png)

**Comment by RogerTarani** [comment]
Thanks.
