### ISSUE TITLE
bwrap: No permissions to creating new namespace

### ISSUE THREAD

**Issue by anonymous133** [projectatomic/bubblewrap#324]
This happens with the newest Version on Arch (v 0.3.3-2) with Kernel: 5.1.16.a-1-hardened. 

Flatpak apps stopped to work for me. Solution is to downgrade to 0.3.1-1. Apps run normally with that version.

Is this expected behaviour? 

$ flatpak run io.freetubeapp.FreeTube
bwrap: No permissions to creating new namespace, likely because the kernel does not allow non-privileged user namespaces. On e.g. debian this can be enabled with 'sysctl kernel.unprivileged_userns_clone=1'.
error: ldconfig failed, exit status 256

Thank you!

**Comment by smcv** [comment]
I would recommend talking to your distributor (in your case Arch Linux) about how they have configured bubblewrap (setuid root or not) and the kernel (whether unprivileged users are allowed to create user namespaces: always, never, or subject to runtime control), and whether this has changed recently.

For what it's worth, a setuid-root bubblewrap 0.3.3 is still working for me on Debian, and I think Arch Linux uses essentially the same kernel patch as Debian to put unprivileged user namespace creation under runtime control.

**Comment by anonymous133** [comment]
Alright, thank you!

**Comment by smcv** [comment]
The three combinations that make most sense are:

* same as Red Hat Enterprise Linux: kernel always restricts user namespace creation, and bwrap is setuid root
* same as Debian: kernel can be configured to restrict user namespace creation (either on or off by default), and bwrap is setuid root
* same as Fedora/Ubuntu: kernel never restricts user namespace creation, and bwrap is not setuid root

If the kernel never restricts user namespace creation but bwrap is unnecessarily setuid root anyway, like the first few versions of bubblewrap seen in Ubuntu, then that is redundant but will also work fine.

My understanding was that Arch Linux had the same behaviour for this as Debian, but I am not an Arch Linux user or developer, so I might be out of touch with how they do it.

**Comment by anonymous133** [comment]
I reevaluated for me personally that I won't use flatpak anymore and stick to pacman and AUR.

**Comment by smcv** [comment]
The Arch Linux maintainer of bubblewrap seems to have disabled setuid mode. https://git.archlinux.org/svntogit/packages.git/commit/trunk?h=packages/bubblewrap&id=bf828975d4cf5654af7fabe0452e323636191748 doesn't say why they did this, and Arch Linux kernels still seem to have the same behaviour as Debian kernels.

It seems an odd choice for a distribution to contain a bubblewrap package that has not been configured so that it works, and I would suggest reporting this as an Arch Linux packaging bug.

**Comment by madaidan** [comment]
This isn't a bug. Arch used to have unprivileged user namespaces disabled but recently they re-enabled them which got rid of the need for bubblewrap to be setuid. The linux-hardened kernel still keeps unprivileged user namespaces disabled so bubblewrap won't work by default. You can give the setuid permission back by running `chmod u+s /usr/bin/bwrap`
