### ISSUE TITLE
--share-user default even without userns

### ISSUE THREAD

**Issue by cgwalters** [projectatomic/bubblewrap#36]
Basically I built on RHEL7.2, tried to run the demo, but needed:

```
diff --git a/demos/bubblewrap-shell.sh b/demos/bubblewrap-shell.sh
index da06d49..a445660 100755
--- a/demos/bubblewrap-shell.sh
+++ b/demos/bubblewrap-shell.sh
@@ -5,6 +5,7 @@ set -euo pipefail
       --dir /tmp \
       --proc /proc \
       --dev /dev \
+      --share-user \
       --ro-bind /etc/resolv.conf /etc/resolv.conf \
       --symlink usr/lib /lib \
       --symlink usr/lib64 /lib64 \
```

I'm leaning a bit towards making `--share-user` the default, and you always have to say `--unshare-user` if you want that ?

Maybe we have a `--unshare-user-if-possible` ?  Dunno.

If we don't have a DWIM in bwrap, the ergonomics are going to be annoying for consuming tools that want to support both modes.

**Comment by rhatdan** [comment]
Yes --share-user should be default.
