### ISSUE TITLE
Release model

### ISSUE THREAD

**Issue by cgwalters** [projectatomic/bubblewrap#74]
We haven't yet done a release, I think we should.

Maybe let's use `0.1.0` implementing [semver](http://semver.org/) ?

I've been using `YEAR.SERIAL` for ostree since I don't think semver applies as much to non-libraries, but bubblewrap is kind of a library.

**Comment by alexlarsson** [comment]
That sounds like a good plan to me.

How are we going on the security review front though? Would like to have something there before a release.

**Comment by cgwalters** [comment]
I dunno.  I don't think secreview should block a `0.1` stream though.  My perspective is bwrap is as secure as linux-user-chroot, and I'd like to kill that.

Are you OK if I push a `0.1.0` tag?  Do you want to do it?

**Comment by alexlarsson** [comment]
Go ahead and push it

**Comment by rhatdan** [comment]
Also trying to replace seunshare with bwrap.  Just dealing with some SELinux issues.

**Comment by cgwalters** [comment]
https://github.com/projectatomic/bubblewrap/releases/tag/v0.1.0
