### ISSUE TITLE
(Enhancement) Make `--unshare-uts` generally useful.

### ISSUE THREAD

**Issue by Yawning** [projectatomic/bubblewrap#93]
There's not much point to creating a new UTS namespace when the hostname/domainname are inherited, and `CAP_SYS_ADMIN` is dropped before user code is executed, making it generally "hard" to change the values.

It would be nice (and straight forward) to have the capability to set the hostname/domainname in the sandboxed child namespace.

**Comment by cgwalters** [comment]
Marking closed per https://github.com/projectatomic/bubblewrap/pull/94
